version: '2'
volumes:
  dbdata:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS users_db; CREATE DATABASE IF NOT EXISTS groups_db;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "