version: '2'
volumes:
  dbdata:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_ROOT_PASSWORD: root