---
resources:
  - name: git-resource
    type: git
    source:
      uri: https://github.com/YuriiLushchyk/payment-splitter-project.git
      branch: master

jobs:
  - name: job-test
    public: true
    plan:
      - get: git-resource
      - task: run-tests
        file: git-resource/ci/test.yml