---
resources:
  - name: resource-source
    type: git
    source:
      uri: https://github.com/YuriiLushchyk/payment-splitter-project.git
      branch: master

jobs:
  - name: job-test
    public: true
    plan:
      - get: resource-source
      - task: run-tests
        file: resource-source/ci/test.yml